name: Docker Build
'on':
  workflow_dispatch:
    inputs:
      tags:
        description: image version
        required: true
jobs:
  docker-build-push:
    name: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: scripts/docker/
          push: true
          tags: icenetworkio/snow:${{ github.event.inputs.tags }}
